export const ALL_BOOKS_REQUEST = 'ALL_BOOKS_REQUEST'
export const ALL_BOOKS_SUCCESS = 'ALL_BOOKS_SUCCESS'
export const ALL_BOOKS_FAIL = 'ALL_BOOKS_FAIL'


export const BOOK_DETAILS_REQUEST = 'BOOK_DETAILS_REQUEST'
export const BOOK_DETAILS_SUCCESS = 'BOOK_DETAILS_SUCCESS'
export const BOOK_DETAILS_FAIL = 'BOOK_DETAILS_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'